version: "3"

services:
  "dynamodb":
    image: amazon/dynamodb-local:1.13.5
    networks:
      - dynamodb
    ports:
      - 8000:8000
    user: root:root
    command: -jar DynamoDBLocal.jar -dbPath /var/db
    volumes:
      - data:/var/db:rw

networks:
  dynamodb:

volumes:
  data: 