service: rust-serverless
provider:
  name: aws
  runtime: rust
  region: eu-central-1
plugins:
  - serverless-rust
package:
  individually: true
functions:
  retrieve:
    handler: retrieve
    events:
      - http:
          path: /retrieve
          method: GET
  store:
    handler: store
    events:
      - http:
          path: /store
          method: GET
