AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Rust Serverless Tests

Resources:
  RetrieveFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Retrieve
      Handler: does.not.matter
      Runtime: provided
      MemorySize: 512
      CodeUri: retrieve.zip
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /retrieve
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !GetAtt Datastore.Arn
  StoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Store
      Handler: does.not.matter
      Runtime: provided
      MemorySize: 512
      CodeUri: store.zip
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /store
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !GetAtt Datastore.Arn
  Datastore:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: firstName
          AttributeType: S
      KeySchema:
        - AttributeName: firstName
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
Outputs:
  HelloAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  RetrieveFunction:
    Description: "Retrieve Lambda Function ARN"
    Value: !GetAtt RetrieveFunction.Arn
  RetrieveFunctionIamRole:
    Description: "Implicit IAM Role created for Retrieve function"
    Value: !GetAtt RetrieveFunction.Arn
  StoreFunction:
    Description: "Store Lambda Function ARN"
    Value: !GetAtt StoreFunction.Arn
  StoreFunctionIamRole:
    Description: "Implicit IAM Role created for Store function"
    Value: !GetAtt StoreFunction.Arn