[package]
name = "store"
version = "0.1.0"
authors = ["Matt Brown <matt@ederoyd.co.uk>"]
edition = "2018"

[dependencies]
lambda = { git = "https://github.com/awslabs/aws-lambda-rust-runtime/", rev = "c36409c5e65f994c7ff48510cd111905b4aa77c9" }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
serde_derive = "^1"
log = "^0.4"
simple_logger = "^1.5"
simple-error = "^0.1"
rusoto_core = "0.45.0"
rusoto_dynamodb = "0.45.0"
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
mockall = "0.8.0"

[features]
with-lambda = []
# default = ["with-lambda"]


