[package]
authors = ["Matt Brown <matt@ederoyd.co.uk>"]
edition = "2018"
name = "lambdas"
version = "0.1.0"

[dependencies]
lambda = {git = "https://github.com/awslabs/aws-lambda-rust-runtime/", rev = "13aa8f01813e6949ca91aedafb286591fdf32217"}
lib = {path = "../lib"}
log = "^0.4"
tokio = "^0.2"
serde_json = "^1"

[dev-dependencies]
mockall = "0.8.0"

[features]
with-lambda = []
# default = ["with-lambda"]

[[bin]]
name = "store_event"
path = "src/store_event.rs"

[[bin]]
name = "store_value"
path = "src/store_value.rs"

# [[bin]]
# name = "retrieve"
# path = "src/retrieve.rs"
