[package]
authors = ["Matt Brown <matt@ederoyd.co.uk>"]
edition = "2018"
name = "lambdas"
version = "0.2.0"

[dependencies]
lambda_http = "0.3.0"
lambda_runtime = "0.3.0"
lib = {path = "../lib"}
log = "^0.4.14"
tokio = { version = "1", features = ["full"] }
serde_json = "^1.0.64"

# [dev-dependencies]
# mockall = "0.8.0"

[features]
with-lambda = []

[[bin]]
name = "store_value"
path = "src/store_value.rs"

[[bin]]
name = "retrieve_value"
path = "src/retrieve_value.rs"

