[package]
authors = ["Matt Brown <matt@ederoyd.co.uk>"]
edition = "2018"
name = "lambdas"
version = "0.1.0"

[dependencies]
lambda = {git = "https://github.com/awslabs/aws-lambda-rust-runtime/", rev = "c36409c5e65f994c7ff48510cd111905b4aa77c9"}
lib = {path = "../lib"}
log = "^0.4"
rusoto_core = {version = "0.45.0", default_features = false, features = ["rustls"]}
rusoto_dynamodb = {version = "0.45.0", default_features = false, features = ["rustls"]}
rusoto_s3 = {version = "0.45.0", default_features = false, features = ["rustls"]}
serde = {version = "^1", features = ["derive"]}
serde_derive = "^1"
serde_json = "^1"
simple_logger = "^1.11.0"
tokio = "^0.2"
once_cell = "1.4.1"

[dev-dependencies]
mockall = "0.8.0"

[features]
with-lambda = []
# default = ["with-lambda"]

[[bin]]
name = "store"
path = "src/store.rs"

# [[bin]]
# name = "retrieve"
# path = "src/retrieve.rs"
