[package]
authors = ["Matt Brown <matt@ederoyd.co.uk>"]
edition = "2018"
name = "lambdas"
version = "0.4.0"

[dependencies]
lambda_http = "0.5.1"
lib = { path = "../lib" }
log = "^0.4.14"
tokio = { version = "1", features = ["full"] }
serde_json = "^1.0.68"
aws-config = "^0.9.0"
env_logger = "0.9.0"

# [dev-dependencies]
# mockall = "0.8.0"

# [features]
# with-lambda = []

[[bin]]
name = "store_value"
path = "src/store_value.rs"

[[bin]]
name = "retrieve_value"
path = "src/retrieve_value.rs"
