name: Rust

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
    - name: Install musl
      run: sudo apt-get update && sudo apt-get install -y musl musl-dev musl-tools
    - name: Setup Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: x86_64-unknown-linux-musl
    - name: Test
      run: make test
    - name: Build Release
      run: make release
    - name: Package
      run: make package
    - name: Upload Lambdas
      uses: actions/upload-artifact@v2
      with:
        name: lambdas-${{ runner.os }}.zip
        path: |
          deploy/*.zip
