name: Rust

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v2
    - name: Build
      run: make build
    - name: Test
      run: make test

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v2
    - name: Build
      run: make release
    - name: Package
      run: make package
    - name: Upload Store Lambda
      uses: actions/upload-artifact@v2
      with:
        name: store.zip
        path: deploy/store.zip
    # - name: Upload Terraform
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: main.tf
    #     path: main.tf
